// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC_mcHeWtzdbNX8scHGSFiLNvXrKSigflE',
    appId: '1:1080595396673:web:c04d4f4c356bc27dd2aec0',
    messagingSenderId: '1080595396673',
    projectId: 'pedometer-1020e',
    authDomain: 'pedometer-1020e.firebaseapp.com',
    storageBucket: 'pedometer-1020e.firebasestorage.app',
    measurementId: 'G-54BBEHJ622',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBPfTrj8gfXbA4PrMEOvK4LVCm48U4j7Wg',
    appId: '1:1080595396673:android:783120a624c0eb30d2aec0',
    messagingSenderId: '1080595396673',
    projectId: 'pedometer-1020e',
    storageBucket: 'pedometer-1020e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDRDrEBWg12WnU2qeKNahwRG2ZqTUS-DX0',
    appId: '1:1080595396673:ios:6c1870589028d856d2aec0',
    messagingSenderId: '1080595396673',
    projectId: 'pedometer-1020e',
    storageBucket: 'pedometer-1020e.firebasestorage.app',
    iosBundleId: 'com.nsb.stepCounter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDRDrEBWg12WnU2qeKNahwRG2ZqTUS-DX0',
    appId: '1:1080595396673:ios:6c1870589028d856d2aec0',
    messagingSenderId: '1080595396673',
    projectId: 'pedometer-1020e',
    storageBucket: 'pedometer-1020e.firebasestorage.app',
    iosBundleId: 'com.nsb.stepCounter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC_mcHeWtzdbNX8scHGSFiLNvXrKSigflE',
    appId: '1:1080595396673:web:7f3cc075804fc34ed2aec0',
    messagingSenderId: '1080595396673',
    projectId: 'pedometer-1020e',
    authDomain: 'pedometer-1020e.firebaseapp.com',
    storageBucket: 'pedometer-1020e.firebasestorage.app',
    measurementId: 'G-GKKE44GMC6',
  );
}
